version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_1.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          install-aws-cli: true
          role-arn: 'arn:aws:iam::100243377175/role/VALID-S3-ROLE'
          to: 's3://circlecidemo/prefix'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_1.txt
          to: 's3://my-s3-bucket-name'
workflows:
  s3-example:
    jobs:
      - build

